source 'https://github.com/CocoaPods/Specs.git'
source 'http://gitlab.jucaicat.net/iOS-Framework/Specs.git'
platform :ios, '7.0'

target :'WJWebViewJavascriptBridge-example' do

pod 'WJLoggingCocoaLumberjack'

pod 'WJConfig'

end
