source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yunhaiwu/ios-wj-framework-cocoapods-specs.git'
platform :ios, '7.0'

target :'WJWebViewJavascriptBridge-example' do

pod 'WJLoggingAPI'

pod 'WJConfig'

end
